### ISSUE TITLE
full class hierarchy not captured

### ISSUE THREAD

**Issue by soumith** [iamaziz/PyTorch-docset#1]
Thanks for building the docsets.

I've noticed that searching for something like `torch.autograd.Variable` returns empty, though directly searching for `Variable` finds things.

Same with say torch methods such as `torch.is_tensor`, searching for `is_tensor` or `torch.is_tensor` returns empty.

**Comment by iamaziz** [comment]
That's correct. The reason this happens is because the docset does not support [table of contents](https://kapeli.com/docsets#tableofcontents).

For some reason [doc2dash](https://doc2dash.readthedocs.io/en/stable/usage.html) (which is the easy way to build a full-support "with TOC" docset from sphinx documentation) did not recognize the format of  PyTorch html files! Perhaps this's due to using pre-built html docs, as explained under the [warning here](https://doc2dash.readthedocs.io/en/stable/formats.html#sphinx).

Have to investigate more about doc2dash, or build the TOC manually.

**Comment by iamaziz** [comment]
Just pushed [an updated docset](https://github.com/Kapeli/Dash-User-Contributions/pull/1513) to Dash repo (built using `makefile` in the main PyTorch doc) , it should now support full search with TOC.

Thanks to @lucasb-eyer 

![image](https://user-images.githubusercontent.com/3298308/29278604-40639272-80e3-11e7-9f09-c6da144f855a.png)

**Comment by soumith** [comment]
thats awesome!
